import {
    reducerGenerator
} from './index';

import {
    roomsInitialState,
    roomsActionTypes
} from './../constants';

const reducerToTest = reducerGenerator(
    roomsActionTypes.getRooms,
    roomsActionTypes.setRooms,
    roomsInitialState,
);

describe('tests reducer generated by reducer generator', () => {
    it('responds correctly to request', () => {
        const newState = reducerToTest(roomsInitialState, {
            type: roomsActionTypes.getRooms,
        });
        expect(newState.loading).toEqual(true);
    });
    it('responds correctly to set', () => {
        const newState = reducerToTest(roomsInitialState, {
            type: roomsActionTypes.setRooms,
            payload: {
                title: '123',
            },
        });
        expect(newState).toEqual(({
            ...roomsInitialState,
            loading: false,
            title: '123',
        }));
    });
});